import numpy as np
import torch
import os
import math

class EarlyStopping:
    """
    Early stopping for supervised learning.
    Monitors validation loss or accuracy.
    """
    def __init__(
        self,
        dir_path,
        monitor="loss",      # "loss" or "acc"
        patience=7,
        delta=0.0,
        verbose=False
    ):
        assert monitor in ["loss", "acc"]

        self.dir_path = dir_path
        self.monitor = monitor
        self.patience = patience
        self.delta = delta
        self.verbose = verbose

        self.counter = 0
        self.early_stop = False
        self.best_epoch = None

        # Initialize best value
        if monitor == "loss":
            self.best = float("inf")
            self.mode = "min"
        else:  # accuracy
            self.best = -float("inf")
            self.mode = "max"

    def __call__(self, epoch, val_loss, val_acc, model):
        """
        Args:
            epoch (int)
            val_loss (float)
            val_acc (float)
            model (nn.Module)
        """
        current = val_loss if self.monitor == "loss" else val_acc

        improved = (
            current < self.best - self.delta
            if self.mode == "min"
            else current > self.best + self.delta
        )

        if improved:
            self.best = current
            self.best_epoch = epoch
            self.counter = 0
            self.save_checkpoint(epoch, model)
        else:
            self.counter += 1
            if self.verbose:
                print(
                    f"EarlyStopping counter: {self.counter}/{self.patience} "
                    f"(best {self.monitor}: {self.best:.4f})"
                )
            if self.counter >= self.patience:
                self.early_stop = True

    def save_checkpoint(self, epoch, model):
        """Save best model."""
        if self.verbose:
            print(
                f"Validation {self.monitor} improved. "
                f"Saving model at epoch {epoch}."
            )

        checkpoint_path = os.path.join(
            self.dir_path, f"best_model_epoch_{epoch}.pt"
        )
        torch.save(model.state_dict(), checkpoint_path)

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor

def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)

def move_to_device(obj, device):
    if torch.is_tensor(obj):
        return obj.to(device)

    elif isinstance(obj, list):
        return [move_to_device(x, device) for x in obj]

    elif isinstance(obj, tuple):
        return tuple(move_to_device(x, device) for x in obj)

    elif isinstance(obj, dict):
        return {k: move_to_device(v, device) for k, v in obj.items()}

    else:
        return obj

def get_1d_sincos_pos_embed_from_grid(embed_dim, pos):
    """
    embed_dim: output dimension for each position
    pos: a list of positions to be encoded: size (M,)
    out: (M, D)
    """
    assert embed_dim % 2 == 0
    omega = np.arange(embed_dim // 2, dtype=float)
    omega /= embed_dim / 2.
    omega = 1. / 10000**omega   # (D/2,)

    pos = pos.reshape(-1)   # (M,)
    out = np.einsum('m,d->md', pos, omega)   # (M, D/2), outer product

    emb_sin = np.sin(out)  # (M, D/2)
    emb_cos = np.cos(out)  # (M, D/2)

    emb = np.concatenate([emb_sin, emb_cos], axis=1)  # (M, D)
    return emb

def get_1d_sincos_pos_embed(embed_dim, length, cls_token=False):
    """
    length: int of the sequence length
    return:
    pos_embed: [length, embed_dim] or [1+length, embed_dim] (w/ or w/o cls_token)
    """
    positions = np.arange(length, dtype=float)
    pos_embed = get_1d_sincos_pos_embed_from_grid(embed_dim, positions)
    if cls_token:
        pos_embed = np.concatenate([np.zeros([1, embed_dim]), pos_embed], axis=0)
    return pos_embed

def apply_masks(x, mask_indices, is_equal_indices=True):
    '''
    x: (2B, N, E) - input embeddings  
    mask_indices: list of indices for visible and target (predict) patches
    is_equal_indices: to indicate if the indices for both visible and target patchs are the same or not
    '''
    if is_equal_indices:
        _, N, E = x.shape

        # Expand indices for gather
        index = mask_indices.unsqueeze(-1).expand(-1, -1, E)  # (B, m, E)

        # Gather selected patches
        x_selected = torch.gather(x, dim=1, index=index)           # (B, m, E)

        return x_selected
    
    else:
        B = int(len(x) / 2)
        _, N, E = x.shape
        x = x.view(2, B, N, E)

        _, m = mask_indices.shape
        mask_indices = mask_indices.view(2, B, m)   # (K, B, m)

        # Expand indices for gather
        index = mask_indices.unsqueeze(-1).expand(-1, -1, -1, E)  # (K, B, m, E)

        # Gather selected patches
        x_selected = torch.gather(x, dim=2, index=index)           # (K, B, m, E)

        # x_selected = x_selected.permute(1, 0, 2, 3)
        K, B, m, E = x_selected.shape
        x_selected = x_selected.reshape(K*B, m, E)                  # (2B, m, E)

        return x_selected

'''
def apply_masks(x, mask_indices):
    _, _, E = x.shape

    # Expand indices for gather
    index = mask_indices.unsqueeze(-1).expand(-1, -1, E)  # (B, m, E)

    # Gather selected patches
    x_selected = torch.gather(x, dim=1, index=index)           # (B, m, E)

    return x_selected'''