import numpy as np
import torch
# import os
import math
# from tqdm import tqdm

def get_jepa_param_groups(model):
    decay = []
    no_decay = []
    for name, param in model.named_parameters():
        if not param.requires_grad:
            continue
        # Do not decay biases or normalization layers
        if len(param.shape) == 1 or name.endswith(".bias"):
            no_decay.append(param)
        else:
            decay.append(param)
    return [
        {"params": decay, "weight_decay": 1e-2},    # following AdamW's default value
        {"params": no_decay, "weight_decay": 0.0} # locked at 0.0
    ]

def get_classifier_param_groups(model, enc_lr, clf_lr, weight_decay):
    # Groups for the Encoder
    enc_decay = []
    enc_no_decay = []
    
    # Groups for the Classifier
    clf_decay = []
    clf_no_decay = []

    for name, param in model.named_parameters():
        if not param.requires_grad:
            continue

        # Decide which LR group it belongs to
        if "context_encoder" in name:
            target_decay = enc_decay
            target_no_decay = enc_no_decay
        else:
            target_decay = clf_decay
            target_no_decay = clf_no_decay

        # Decide if it should be decayed (Weights vs Biases/Norms)
        if len(param.shape) == 1 or name.endswith(".bias"):
            target_no_decay.append(param)
        else:
            target_decay.append(param)

    return [
        {"params": enc_decay, "lr": enc_lr, "weight_decay": weight_decay},
        {"params": enc_no_decay, "lr": enc_lr, "weight_decay": 0.0},
        {"params": clf_decay, "lr": clf_lr, "weight_decay": weight_decay},
        {"params": clf_no_decay, "lr": clf_lr, "weight_decay": 0.0},
    ]

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor

def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)

def move_to_device(obj, device):
    if torch.is_tensor(obj):
        return obj.to(device)

    elif isinstance(obj, list):
        return [move_to_device(x, device) for x in obj]

    elif isinstance(obj, tuple):
        return tuple(move_to_device(x, device) for x in obj)

    elif isinstance(obj, dict):
        return {k: move_to_device(v, device) for k, v in obj.items()}

    else:
        return obj

def get_1d_sincos_pos_embed_from_grid(embed_dim, pos):
    """
    embed_dim: output dimension for each position
    pos: a list of positions to be encoded: size (M,)
    out: (M, D)
    """
    assert embed_dim % 2 == 0
    omega = np.arange(embed_dim // 2, dtype=float)
    omega /= embed_dim / 2.
    omega = 1. / 10000**omega   # (D/2,)

    pos = pos.reshape(-1)   # (M,)
    out = np.einsum('m,d->md', pos, omega)   # (M, D/2), outer product

    emb_sin = np.sin(out)  # (M, D/2)
    emb_cos = np.cos(out)  # (M, D/2)

    emb = np.concatenate([emb_sin, emb_cos], axis=1)  # (M, D)
    return emb

def get_1d_sincos_pos_embed(embed_dim, length, cls_token=False):
    """
    length: int of the sequence length
    return:
    pos_embed: [length, embed_dim] or [1+length, embed_dim] (w/ or w/o cls_token)
    """
    positions = np.arange(length, dtype=float)
    pos_embed = get_1d_sincos_pos_embed_from_grid(embed_dim, positions)
    if cls_token:
        pos_embed = np.concatenate([np.zeros([1, embed_dim]), pos_embed], axis=0)
    return pos_embed

def apply_masks(x, mask_indices):
    B = int(len(x) / 2)
    _, N, E = x.shape
    x = x.view(2, B, N, E)

    _, m = mask_indices.shape
    mask_indices = mask_indices.view(2, B, m)   # (2B, m) -> (K, B, m)

    # Expand indices for gather
    index = mask_indices.unsqueeze(-1).expand(-1, -1, -1, E)  # (K, B, m, E)

    # Gather selected patches
    x_selected = torch.gather(x, dim=2, index=index)           # (K, B, m, E)

    # x_selected = x_selected.permute(1, 0, 2, 3)
    K, B, m, E = x_selected.shape
    x_selected = x_selected.reshape(K*B, m, E)                  # (2B, m, E)

    return x_selected

def apply_channel_masks(x, mask_indices):
    '''
    x: (B, L, C, E)
    mask_indices: (B, m)
    '''

    _, L, _, E = x.shape

    # Expand indices for gather
    index = mask_indices.unsqueeze(1).unsqueeze(-1).expand(-1, L, -1, E)  # (B, 1, m, E)

    # Gather selected patches
    x_selected = torch.gather(x, dim=2, index=index)           # (K, B, m, E)

    # x_selected = x_selected.permute(1, 0, 2, 3)
    B, L, m, E = x_selected.shape
    x_selected = x_selected.reshape(B, L, m*E)                  # (2B, m, E)

    return x_selected

# Pass JEPA model
def extract_embeddings(model, dataloader, device, dim=1):
    model.eval()
    embeddings = []
    labels = []

    with torch.no_grad():
        for batch in dataloader:
            batch = move_to_device(batch, device)
            x = batch["windows"]        # (B, L, C)
            y = batch["labels"][1]       # (B,)
            
            # Forward through encoder only
            z = model.context_encoder(x)   # (2B, N, E)
            B, N, E = z.shape
            B_half = B // 2
            z = z.reshape(B_half, 2, N, E)      # (B, 2, N, E)
            z = z.reshape(B_half, 2*N, E)       # (B, 2N, E)

            z = z.mean(dim=dim)              # (B, E)

            embeddings.append(z.cpu().numpy())
            labels.append(y.cpu().numpy())

    embeddings = np.concatenate(embeddings, axis=0)
    labels = np.concatenate(labels, axis=0)

    return embeddings, labels

# method = inverse, balanced, square-root
# dataset = 'SBHARPT' or 'FORTH-TRACE'
def get_class_weight(method, dataset='SBHARPT'):
    if dataset == 'SBHARPT':
        class_counts = torch.tensor(
            [578, 566, 536, 666, 679, 706, 48, 36, 58, 46, 51, 55],
            dtype=torch.float
        )

    else:
        class_counts = torch.tensor(
            [842, 827, 1396, 676, 59, 66], 
            dtype=torch.float
        )

    if method == 'inverse':
        weights = 1.0 / class_counts    # inverse
        return weights / weights.sum() * len(class_counts)   # normalize
    
    elif method == 'balanced':
        N = class_counts.sum()
        C = len(class_counts)
        return N / (C * class_counts)

    elif method == 'square-root':
        weights = 1 / torch.sqrt(class_counts)
        return weights / weights.mean()


# def apply_masks(x, mask_indices, is_equal_indices=True):
    '''
    x: (B, N, E) - input embeddings  
    mask_indices: list of indices for visible and target (predict) patches
    is_equal_indices: to indicate if the indices for both visible and target patchs are the same or not
    '''
    '''
    _, N, E = x.shape

    # Expand indices for gather
    index = mask_indices.unsqueeze(-1).expand(-1, -1, E)  # (B, m, E)

    # Gather selected patches
    x_selected = torch.gather(x, dim=1, index=index)           # (B, m, E)

    return x_selected'''
        


